[project]
name = "her-voice"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
langchain = "^0.3.0"
langchain-anthropic = "^0.3.5"
langchain-groq = "^0.2.3"
langchain-google-genai = "^2.0.11"
langchain-google-vertexai = "^2.0.13"
langchain-openai = "^0.3.5"
langchain-deepseek = "^0.1.2"
langchain-ollama = "^0.2.0"
langchain-pymupdf4llm = "^0.2.0"
langchain-huggingface = "^0.1.2"
langchain-community = "^0.3.21"
langgraph = "0.2.56"
scikit-learn = "^1.6.1"
pandas = "^2.1.0"
numpy = "^1.24.0"
python-dotenv = "1.0.0"
matplotlib = "^3.9.2"
tabulate = "^0.9.0"
colorama = "^0.4.6"
questionary = "^2.1.0"
rich = "^13.9.4"
streamlit = "^1.42.2"
streamlit-feedback = "^0.1.4"
jq = "^1.8.0"
pydantic = "^2.11.3"
fastapi = "^0.115.12"
uvicorn = "^0.34.1"

[tool.poetry]
packages = [
    { include = "hervoice", from = "src" },
]

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
black = "^23.7.0"
isort = "^5.12.0"
flake8 = "^6.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 420
target-version = ['py312']
include = '\.pyi?$'